# Generated by Django 5.2.1 on 2025-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(null=True, verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(null=True, verbose_name='Fecha de Actualización')),
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, verbose_name='Nombre')),
                ('image', models.CharField(max_length=256, verbose_name='Imagen')),
                ('route', models.CharField(max_length=256, verbose_name='Ruta')),
            ],
            options={
                'verbose_name': 'ROLE',
                'verbose_name_plural': 'ROLES',
                'db_table': 'ROLES',
            },
        ),
    ]
