# Generated by Django 5.2 on 2025-05-07 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHasRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, to='roles.rolemodel')),
            ],
            options={
                'db_table': 'USER_HAS_ROLES',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(null=True, verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=256, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('image', models.CharField(max_length=256, null=True, verbose_name='Imagen')),
                ('password', models.CharField(max_length=256, verbose_name='Contraseña')),
                ('notification_token', models.CharField(max_length=256, null=True, verbose_name='Token de Notificación')),
                ('role', models.ManyToManyField(related_name='USERS', through='users.UserHasRoles', to='roles.rolemodel')),
            ],
            options={
                'verbose_name': 'USER',
                'verbose_name_plural': 'USERS',
                'db_table': 'USERS',
            },
        ),
        migrations.AddField(
            model_name='userhasroles',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='users.usermodel'),
        ),
        migrations.AlterUniqueTogether(
            name='userhasroles',
            unique_together={('id_user', 'id_role')},
        ),
    ]
