# Generated by Django 5.2 on 2025-05-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='create_at',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='update_at',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Actualización'),
        ),
    ]
