# Generated by Django 5.1.2 on 2024-11-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchOfficesModel',
            fields=[
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('country', models.CharField(max_length=200, verbose_name='Pais')),
                ('state_province', models.CharField(max_length=200, verbose_name='Provincia o Estado')),
                ('city', models.CharField(max_length=200, verbose_name='Ciudad')),
                ('address', models.CharField(max_length=200, verbose_name='Dirección')),
                ('postal_code', models.CharField(default='S/N', max_length=200, verbose_name='Codigo Postal')),
                ('cellphone_number', models.CharField(max_length=50, verbose_name='Celular')),
                ('phone_number', models.CharField(default='Sin Telefono Convencional', max_length=50, verbose_name='Telefono')),
                ('email', models.CharField(default='No Posee email', max_length=100, verbose_name='E-mail')),
                ('img', models.ImageField(blank=True, null=True, upload_to='persons/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'BRANCH_OFFICE',
                'verbose_name_plural': 'BRANCH_OFFICES',
                'db_table': 'APP_BRANCH_OFFICES',
            },
        ),
    ]
