# Generated by Django 5.1.2 on 2024-11-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_offices', '0002_alter_branchofficesmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchofficesmodel',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nombre'),
        ),
    ]
