# Generated by Django 5.1.3 on 2024-12-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_offices', '0004_alter_branchofficesmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchofficesmodel',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='branchoffices/', verbose_name='Imagen'),
        ),
    ]
