# Generated by Django 5.1.2 on 2025-04-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_offices', '0005_alter_branchofficesmodel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchofficesmodel',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='branchoffices/', verbose_name='Imagen'),
        ),
    ]
