# Generated by Django 5.2.1 on 2025-05-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('status_description', models.CharField(default='No existe descripción', max_length=256, verbose_name='Descripción del Estado')),
                ('create_at', models.DateTimeField(null=True, verbose_name='Fecha de Creación')),
                ('update_at', models.DateTimeField(null=True, verbose_name='Fecha de Actualización')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=256, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('image', models.ImageField(default='default.jpg', upload_to='users/', verbose_name='Imagen')),
                ('password', models.CharField(max_length=256, verbose_name='Contraseña')),
                ('notification_token', models.CharField(max_length=256, null=True, verbose_name='Token de Notificación')),
            ],
            options={
                'verbose_name': 'USER',
                'verbose_name_plural': 'USERS',
                'db_table': 'USERS',
            },
        ),
    ]
