# Generated by Django 5.2.1 on 2025-05-26 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHasRolesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.CASCADE, to='roles.rolemodel')),
                ('id_user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='users.usermodel')),
            ],
            options={
                'db_table': 'USER_HAS_ROLES',
                'unique_together': {('id_user', 'id_role')},
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.ManyToManyField(related_name='USERS', through='users.UserHasRolesModel', to='roles.rolemodel'),
        ),
    ]
